launch:
	g++ Game.cpp resource/MainMenu.cpp resource/mainGame.cpp -o Game.exe -lsfml-graphics -lsfml-window -lsfml-system -Wall
	./Game.exe
installation:
	sudo apt-get install gcc
	sudo apt-get install libsfml-dev
	g++ Game.cpp resource/MainMenu.cpp resource/mainGame.cpp -o Game.exe -lsfml-graphics -lsfml-window -lsfml-system -Wall
	./Game.exe